- hosts: nodes 
  become: yes
  tasks:
  - name: ensure Docker is installed
    apt:
      name: docker.io
      state: latest
      update_cache: yes
    
  - name: ensure Docker-compose is installed
    apt: 
      name: docker-compose
      state: latest
      update_cache: yes
  
  - name: Add user to Docker group
    user:
      name: vagrant
      groups: docker
